### ISSUE TITLE
Support Docker 1.3.3

### ISSUE THREAD

**Issue by stub42** [whitmo/jujubox#12]
Most charmers are running Ubuntu and use package installations. Docker in Ubuntu 15.04 is 1.3.3, so we should be targetting that version.

**Comment by stub42** [comment]
I've smooshed the Dockerfile and CharmersDockerfile together, and the only other change needed was replacing the = with whitespace in the ENV statement:

FROM ubuntu:14.04
MAINTAINER Whit Morriss whit.morriss@canonical.com

ADD setup.sh /setup.sh
RUN /setup.sh

RUN mkdir /home/ubuntu/.juju
RUN mkdir /home/ubuntu/trusty
RUN mkdir /home/ubuntu/precise

VOLUME ["/home/ubuntu/.juju"]

#ADD patchcontainer.sh /patchcontainer.sh
ADD run.sh /run.sh
ADD cleanup.sh /cleanup.sh
ADD charming-setup.sh /charming-setup.sh

RUN /charming-setup.sh
RUN /cleanup.sh
CMD /run.sh

FROM whitmo/jujubox:latest

VOLUME ["/home/ubuntu/.juju"]
ENV JUJU_REPOSITORY /home/ubuntu/charm-repo
VOLUME [${JUJU_REPOSITORY}]
RUN apt-get install -qy gcc cython git make
ADD install-review-tools.sh /install-review-tools.sh
RUN /install-review-tools.sh
CMD /run.sh

**Comment by lazypower** [comment]
@stub42 We're tracking the docker edition from upstream, which at time of writing is 1.5.x

**Comment by whitmo** [comment]
@stub42 thanks for the input!

ATM we are going to separate the repositories for jujubox and charmbox to allow for the docker hub system to more easily ingest changes.  The idea behind having separate files (and now repos) is size and function.   the ubuntu image is fairly large to start with (188mb) and much of the charming tools blow it up quite a bit more (charm box clocks in around 800mb).

**Comment by whitmo** [comment]
@stub42 wrt targetting, I gently disagree.  support where possible yes, but 1.3.3 is pretty old for docker and installing lxc-docker at a more current version is not onerous.

**Comment by whitmo** [comment]
@stub42 do you hit issues with 1.3.3?

**Comment by stub42** [comment]
1.3.3 seems to work. I did get one surprising segfault, but I cannot confirm it is related.

**Comment by stub42** [comment]
It has been happily working with 1.3.3. It was trivial to build my own image btw. so if the branch is compatible you could have both worlds supported.
