### ISSUE TITLE
Unsupported bzr in play

### ISSUE THREAD

**Issue by stub42** [whitmo/jujubox#14]
It seems bzr 2.7dev1 is installed, rather than the supported 2.6 release.

**Comment by stub42** [comment]
Nope, that is my problem. 2.7 is the correct version.

**Comment by johnsca** [comment]
There was a problem with bundletester being tagged to use ==2.6.0, which I corrected to use >=2.6.0 to resolve the error I suspect you saw.

Also note that I forked charmbox to https://github.com/juju-solutions/charmbox/ to maintain the container for CI and review separately.  We should clean up the CharmboxDockerfile bits from this repo.
